services:
  app:
    container_name: web-rekrutmen
    image: web-rekrutmen:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    restart: unless-stopped
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro