version: '3'

services:
    app:
        image: web-rekrutmen:v1
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'web-rekrutmen'
        tty: true
        stdin_open: true
        restart: 'unless-stopped'
        ports:
            - '30100:3000'